DROP TABLE IF EXISTS cache_entry;
CREATE TABLE IF NOT EXISTS cache_entry (
    key VARCHAR(1024) PRIMARY KEY,
    value TEXT NOT NULL,
    ttl INTEGER NOT NULL DEFAULT 0,
    created INTEGER NOT NULL DEFAULT 0
);
